### PR TITLE
Fixes for languages

### PR DESCRIPTION
**Pull request by gade01**
This will hopefully fix all language bugs.
Fingers crossed the workflow will not change anything after this PR.

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Looks good, and CI is green!

**Comment by garbear** [comment]
My bad, I foobarred the PR by bumping the version before it was merged! Will fix and merge.

**Comment by garbear** [comment]
Fixed by hand, and released a new version. @gade01 How do things look?

**Comment by gade01** [comment]
@garbear Everything looks great now. Thanks.

**Pull request closed without merging**
